algoritmo ""
// Função :
// Autor :
// Data : 16/09/2020
// Seção de Declarações 
var
numero jogadores,i:inteiro
a,soma,media:real
inicio
//entrada
soma<-0
Escreval("Digite o numero de jogadores: ")
leia(numero jogadores

para 1 de 1 ate numero jogadores faca
escreval("Digite a altura do 1 jogador: ")
leia(a)

soma<-soma+a
fimpara

media<-soma/numero jogadores
escreval("A altura media do time é: ",media)
fimalgoritmo
